dashboard/urls.py
from django.conf.urls.defaults import include, patterns, url
from django.contrib import admin
from django.contrib.admin.sites import NotRegistered
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

from .views import AuthComplete


admin.autodiscover()

try:
    admin.site.unregister(Site)
except NotRegistered:
    pass
try:
    admin.site.unregister(User)
except NotRegistered:
    pass

from django.http import HttpResponse
def login_error(request, *args, **kwargs):
    return HttpResponse('LOGIN ERROR!')

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^holiday/', include('holiday.urls')),
    url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='login'),
    url(r'^login-error', login_error),
    # url(r'^movie-club/', include('imc.urls')),
    url(r'^shopping-list/', include('status.modules.shoppinglist.urls')),
    url(r'^status/', include('status.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^complete/(?P<backend>[^/]+)/$', AuthComplete.as_view()),
    url(r'', include('social_auth.urls')),
)

urlpatterns += staticfiles_urlpatterns()

holiday/urls.py
from django.conf.urls.defaults import patterns, url


import views

urlpatterns = patterns('holiday.views',
    url(r'^$', views.HomeView.as_view(), name='holiday_index'),
    url(r'^add/$', 'make_holiday_request', name='holiday_make_request'),
    url(r'^calendar/$', views.HolidayCalendar.as_view(), name='holiday_calendar_view'),
    url(r'^management/all/$', views.AllPendingRequestsList.as_view(), name='holiday_all_pending'),
    url(r'^management/$', views.PendingRequestsList.as_view(), name='holiday_request_inbox'),
    url(r'^users/$', views.EmployeeList.as_view(), name='holiday_employee_list'),
    url(r'^users/(?P<username>\w+)/$', views.EmployeeRequestsList.as_view(), name='holiday_user'),
    url(r'^(?P<pk>\d+)/$', 'request_details', name='holiday_request_details'),
)

imc/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic import DetailView

from imc.models import Movie
from imc.views import Current, GroupRating, Index, Pool, Previous, Submit, Widget

urlpatterns = patterns('imc.views',
    url(r'^$', Index.as_view(), name='movie-index'),
    url(r'^current/$', Current.as_view(), name='movie-current'),
    url(r'^group/$', GroupRating.as_view(), name='movie-group-rating'),
    url(r'^pool/$', Pool.as_view(), name='movie-pool'),
    url(r'^previous/$', Previous.as_view(), name='movie-previous'),
    url(r'^submit/$', Submit.as_view(), name='movie-submit'),
    url(r'^widget/$', Widget.as_view(), name='movie-widget'),
    url(r'^(?P<slug>.*)/$', DetailView.as_view(model=Movie), name='movie'),
)

status/modules/weather/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('status.modules.weather.views',
    url(r'', 'index'),
)

holiday/models.py
import datetime

from django.db import models
from django.contrib.sites.models import Site
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.utils.dateformat import format

from incuna.utils.mail import render_to_send_mail
from profiles.models import Profile


DATE_FORMAT = '%Y-%m-%d'

if not hasattr(settings, 'HOLIDAY_YEAR_START_DAY'):
    settings.HOLIDAY_YEAR_START_DAY = 1
if not hasattr(settings, 'HOLIDAY_YEAR_START_MONTH'):
    settings.HOLIDAY_YEAR_START_MONTH = 1


def get_year_start_end(yearoffset=0):
    now = datetime.date.today()
    yearstart = datetime.date(day=settings.HOLIDAY_YEAR_START_DAY, month=settings.HOLIDAY_YEAR_START_MONTH, year=now.year)
    if yearstart > now:
        yearstart = datetime.date(day=yearstart.day, month=yearstart.month, year=yearstart.year - 1)
    yearstart = datetime.date(day=yearstart.day, month=yearstart.month, year=yearstart.year + yearoffset)
    yearend = datetime.date(day=yearstart.day, month=yearstart.month, year=yearstart.year + 1)
    return yearstart, yearend


class HolidayRequestManager(models.Manager):
    def get_query_set(self):
        return super(HolidayRequestManager, self).get_query_set().annotate(start_date=models.Min('holiday__date'))


class HolidayRequest(models.Model):
    """A Request for holiday/s."""
    PENDING_STATUS = 0
    ACCEPTED_STATUS = 1
    DENIED_STATUS = 2
    STATUS_CHOICES = (
        (PENDING_STATUS, 'Pending'),
        (ACCEPTED_STATUS, 'Accepted'),
        (DENIED_STATUS, 'Denied')
    )
    employee = models.ForeignKey(Profile)
    status = models.IntegerField(_('status'), choices=STATUS_CHOICES, default=0)
    date_made = models.DateTimeField(_('request date'), auto_now_add=True)
    administrator = models.ForeignKey(Profile, blank=True, null=True, related_name='admin_set')
    employee_comment = models.TextField(_('Comments'), blank=True, null=True)
    manager_comment = models.TextField(_('Comments'), blank=True, null=True)

    objects = HolidayRequestManager()

    #class Meta():
    #    ordering = ['-start_date',]

    def start_day(self):
        try:
            return self.holiday_set.all()[0]
        except IndexError:
            return None

    def requested_days(self):
        return Holiday.objects.filter(holiday_request__employee__exact=self.employee, holiday_request__exact=self)

    def days_requested_total(self):
        alldays = self.requested_days()
        return alldays.count() - (alldays.filter(half_day__exact=True).count() * 0.5)

    def days_requested_count(self, yearoffset=0):
        yearstart, yearend = get_year_start_end(yearoffset)
        qs = self.requested_days().filter(date__gte=yearstart, date__lt=yearend)
        return qs.count() - (qs.filter(half_day__exact=True).count() * 0.5)

    def __unicode__(self):
        return u"request for %s days holiday" % (self.days_requested_total())

    def send_request_email(self):
        site = Site.objects.get_current()
        mailextras = {
                     'hol_req': self,
                     'site': site,
                     }
        render_to_send_mail(recipient_list=(self.employee.manager.email,), template='holiday/request_email.txt', extra_context=mailextras, subject='Holiday Request')

    def send_confirmation_email(self):
        site = Site.objects.get_current()
        mailextras = {
                     'hol_req': self,
                     'site': site,
                     }
        render_to_send_mail(recipient_list=(self.employee.email,), template='holiday/confirmation_email.txt', extra_context=mailextras, subject='Re: Holiday Request')

#    def save(self, *args, **kwargs):
#        """
#        Try saving a couple of times (sometimes the google code crashes here :/)
#        """
#        for i in xrange(10):
#            try:
#                super(HolidayRequest, self).save(*args, **kwargs)
#                break
#            except RequestError:
#                pass


class Holiday(models.Model):
    """A holiday to be taken off."""
    holiday_request = models.ForeignKey(HolidayRequest)
    date = models.DateField(_('day off'))
    half_day = models.BooleanField(_('half day'), default=False)

    class Meta():
        ordering = ['date']

    def __unicode__(self):
        if self.half_day:
            return u"%s (half day)" % (format(self.date, settings.DATE_FORMAT))
        else:
            return u"%s" % (format(self.date, settings.DATE_FORMAT))


class BankHoliday(models.Model):
    """A Bank Holiday. To be excluded from requested holidays"""
    date = models.DateField(_('bank holiday'))
    name = models.CharField(_('name'), default='bank holiday', max_length=255)

    def __unicode__(self):
        return u"%s (%s)" % (self.name, format(self.date, settings.DATE_FORMAT))

    class Meta():
        ordering = ['-date']

#-------

# Google Calendar integration

#-------

# class HolidayRequestCalendarAdapter(CalendarAdapter):
#     """
#     A Calendar Adapter for the Holiday model
#     """
#     def get_event_data(self, instance):
#         """
#         Returns a CalendarEventData object filled with data from the HolidayRequest instance.
#         """
#         holiday_set = list(instance.holiday_set.all())
#         first_hol = holiday_set[0].date
#         last_hol  = holiday_set[-1].date + datetime.timedelta(days=1)
#         start = datetime.datetime(year=first_hol.year,month=first_hol.month,day=first_hol.day)
#         end   = datetime.datetime(year=last_hol.year, month=last_hol.month, day=last_hol.day)

#         title = u"%s holiday" %(instance.employee.get_full_name())
#         half_days = 0

#         content = u""
#         if instance.employee_comment:
#             content+= u"%s commented: %s\n\n" %(instance.employee.get_full_name(), instance.employee_comment)
#         if instance.manager_comment:
#             content+= u"%s commented: %s\n\n" %(instance.administrator.get_full_name(), instance.manager_comment)

#         for day in holiday_set:
#             content += u"%s\n" %(day)
#             if day.half_day:
#                 half_days += 1

#         if half_days:
#             title += u" ("
#             if half_days != len(holiday_set):
#                 title += u"inc "
#             title += u"%d Half Day%s)" % (half_days, "s" if half_days>1 else "")

#         content = Content(text=content)
#         title = Title(text=title)
#         when = [When(
#                     start_time= start.strftime(DATE_FORMAT),
#                     end_time  = end.strftime(DATE_FORMAT)
#                     )]

#         return RawCalendarEventData(
#                                    when    = when,
#                                    title   = title,
#                                    content = content,
#                                    )

#     def can_save(self, instance):
#         return instance.status == 1 and instance.holiday_set.count() > 0
#         #return True

# holiday_request_observer = CalendarObserver(email=settings.HOLIDAY_CALENDAR_EMAIL,
#                                     password=settings.HOLIDAY_CALENDAR_PASSWORD)
# holiday_request_observer.observe(HolidayRequest, HolidayRequestCalendarAdapter())

holiday/views.py
import datetime

from django.http import Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms.formsets import formset_factory
from incuna.utils import class_view_decorator
from django.views.generic import ListView, TemplateView, RedirectView


from holiday.models import HolidayRequest, BankHoliday
from holiday.forms import HolidayForm, HolidaySelectionForm, HolidayRequestAuthForm, HolidayComment
from profiles.models import Profile


# for use with all the @user_passes_test stuff below
def is_manager(user):
    return user.get_profile().is_manager


@class_view_decorator(login_required)
class HomeView(RedirectView):
    def get_redirect_url(self, **kwargs):
        username = self.request.user.username
        return reverse('holiday_user', kwargs={'username': username})


@login_required
def make_holiday_request(request):
    def get_holidays(start_date, days_off):
        days = []
        one_day = datetime.timedelta(days=1)
        current = start_date
        bank_holidays = [h.date for h in BankHoliday.objects.filter(date__gte=start_date)]
        while len(days) < days_off:
            if current.weekday() < 5 and current not in bank_holidays:
                days.append({'date': current})
            current += one_day
        return days

    HolidayFormSet = formset_factory(HolidayForm, extra=0)
    context = RequestContext(request)

    # STAGE 2: first form submitted
    if request.POST:
        # STAGE 3: show confirmation
        if 'form-INITIAL_FORMS' not in request.POST:
            hol_sel_form = HolidaySelectionForm(request.POST)

            if hol_sel_form.is_valid():
                #holidays
                initial_data = get_holidays(hol_sel_form.cleaned_data['start_date'], hol_sel_form.cleaned_data['days_off'])
                form_set = HolidayFormSet(initial=initial_data)
                context['form_set'] = form_set
                #holiday request (comment)
                comment_form = HolidayComment(initial={'comment': hol_sel_form.cleaned_data['employee_comment']})
                context['comment_form'] = comment_form
            else:
                context.update({'hol_sel_form': hol_sel_form})
        # STAGE 4: accept confirmation
        else:
            form_set = HolidayFormSet(request.POST)
            comment_form = HolidayComment(request.POST)
            context['form_set'] = form_set
            if form_set.is_valid() and comment_form.is_valid():
                holiday_request = HolidayRequest(employee=request.user)
                holiday_request.employee_comment = comment_form.cleaned_data['comment']
                holiday_request.save()
                for form in form_set.forms:
                    instance = form.save(commit=False)
                    instance.holiday_request = holiday_request
                    instance.save()
                holiday_request.send_request_email()
                return HttpResponseRedirect(reverse('holiday_user', kwargs={'username': request.user.username}))
    # STAGE 1: initial form
    else:
        hol_sel_form = HolidaySelectionForm()
        context.update({'hol_sel_form': hol_sel_form})
    return render_to_response('holiday/make_request.html', context)


@class_view_decorator(login_required)
class EmployeeRequestsList(ListView):
    model = HolidayRequest
    template_name = 'holiday/view_status.html'

    def get(self, *args, **kwargs):
        self.employee = self.get_employee()
        return super(EmployeeRequestsList, self).get(*args, **kwargs)

    def get_employee(self):
        employee = get_object_or_404(Profile, username=self.kwargs['username'])
        profile = self.request.user.get_profile()
        if profile.is_manager == False and profile != employee:
            raise Http404('User does not have access')
        return employee

    def get_queryset(self):
        qs = super(EmployeeRequestsList, self).get_queryset()
        return qs.filter(
            employee__pk=self.employee.pk,
            holiday__date__year=datetime.datetime.now().year
        ).order_by('-start_date')

    def get_context_data(self, **kwargs):
        kwargs['employee'] = self.employee
        return super(EmployeeRequestsList, self).get_context_data(**kwargs)


@login_required
def request_details(request, pk):
    qs = HolidayRequest.objects.all()
    context = RequestContext(request)
    #if user is staff , ensure this is one of their requests
    profile = request.user.get_profile()
    if not profile.is_manager:
        qs = qs.filter(employee=profile)
    holiday_request = get_object_or_404(qs, pk=pk)
    #ensure admin employee cannot accept own request for holiday
    if holiday_request.employee != profile and holiday_request.status == 0:
        if request.POST:
            hol_auth_form = HolidayRequestAuthForm(request.POST, instance=holiday_request)
            if hol_auth_form.is_valid():
                holiday_request = hol_auth_form.save(commit=False)
                holiday_request.administrator = profile
                holiday_request.save()
                holiday_request.send_confirmation_email()
                return HttpResponseRedirect(reverse('holiday_user', kwargs={'username': profile.username}))
        else:
            hol_auth_form = HolidayRequestAuthForm(instance=holiday_request)
        context.update({'hol_auth_form': hol_auth_form})
    context.update({
        'holiday_request': holiday_request,
        'holidays': holiday_request.holiday_set,
    })
    return render_to_response('holiday/request_details.html', context)


@class_view_decorator(user_passes_test(is_manager))
class AllPendingRequestsList(ListView):
    model = HolidayRequest
    template_name = 'holiday/pending_requests.html'

    def get_queryset(self):
        qs = super(AllPendingRequestsList, self).get_queryset()
        return qs.filter(status=HolidayRequest.PENDING_STATUS)


class PendingRequestsList(AllPendingRequestsList):
    def get_queryset(self):
        qs = super(PendingRequestsList, self).get_queryset()
        return qs.filter(employee__manager__pk=self.request.user.pk)


@class_view_decorator(user_passes_test(is_manager))
class EmployeeList(ListView):
    model = Profile
    template_name = 'holiday/employee_list.html'


@class_view_decorator(login_required)
class HolidayCalendar(TemplateView):
    template_name = 'holiday/calendar.html'

holiday/templates/holiday/base.html
{% extends "base.html" %}
{% load holidaytags %}

{% block nav %}{{super.nav}}
{% menuitems %}
    {% navitem 'holiday_user' request.user.username %}My Requests{% endnavitem %}
    {% navitem 'holiday_make_request' %}Make Request{% endnavitem %}
    {% if request.user.profile.is_manager %}
    {% navitem 'holiday_request_inbox' %}
        {% with my_pending=request.user.profile.managed_pending_requests %}
            Pending Request Inbox{% if my_pending %} ({{ my_pending.count }}){% endif %}
        {% endwith %}
    {% endnavitem %}
    {% navitem 'holiday_all_pending' %}
        {% all_pending_requests as all_requests %}
            All Pending Requests{% if all_requests %} ({{ all_requests.count }}){% endif %}
    {% endnavitem %}
    {% navitem 'holiday_employee_list' %}All Employees{% endnavitem %}
    {% endif %}
    {% navitem 'holiday_calendar_view' %}Calendar{% endnavitem %}
{% endmenuitems %}
{% endblock %}

holiday/templates/holiday/calendar.html
{% extends "holiday/base.html" %}

{% block title %}Incuna Holiday Requests - Calendar{% endblock %}

{% block content %}
    <h2>You must be signed in to <a href="http://calendar.incuna.com">Incuna Google Calendar</a></h2>
    <iframe src="https://www.google.com/calendar/hosted/incuna.com/embed?showTitle=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;height=600&amp;wkst=2&amp;bgcolor=%23999999&amp;src=holiday%40incuna.com&amp;color=%232952A3&amp;src=en.uk%23holiday%40group.v.calendar.google.com&amp;color=%23B1440E&amp;ctz=Europe%2FLondon"
            style=" border-width:0 " width="940" height="600" frameborder="0" scrolling="no">
        <p>Sorry, your browser doesn't support IFRAME.</p>
    </iframe>
{% endblock %}

holiday/templates/holiday/employee_list.html
{% extends "holiday/base.html" %}
{% load holidaytags %}

{% block title %}Incuna Holiday Requests - Staff{% endblock %}

{% block content %}
    <h2>All Staff</h2>
    {% for o in object_list|dictsort:"last_name" %}
        {% if forloop.first %}
        <table class="standardtable">
            <thead>
            <tr>
                <th>Name</th>
                <th>Manager</th>
                <th>Pending Requests</th>
                <th>Annual Allowance</th>
                <th>Days Left<br />(This/Next Year)</th>
            </tr>
            </thead>
        {% endif %}
            <tr>
                <td><a href="{% url holiday_user username=o.username %}">{{o.get_full_name}}</a></td>
                <td>{{ o.manager.get_full_name }}</td>
                <td>{{ o.pending_requests.count }}</td>
                <td>{{ o.holiday_per_annum }}</td>
                <td>{{ o|days_left_by_year }} / {{ o|days_left_by_year:1 }}</td>
            </tr>
        {% if forloop.last %}</table>{% endif %}
    {% endfor %}
{% endblock %}

holiday/templates/holiday/make_request.html
{% extends "holiday/base.html" %}
{% load holidaytags %}

{% block extrascript %}
    {{ hol_sel_form.media.js }}
    {{ form_set.media.js }}
{% endblock %}

{% block title %}Incuna Holiday Requests - New Request{% endblock %}

{% block content %}
<div class="right">
    <table class="days-left-table">
        <thead>
            <tr><th class="centre noborder" colspan="2">Days Remaining</th></tr>
            <tr>
                <th class="col-this">This Year:</th>
                <th class="col-next">Next Year:</th>
            </tr>
        </thead>
        <tr>
            {% with request.user.get_profile as profile %}
                <td class="col-this bottom">{{ profile|days_left_by_year }}</td>
                <td class="col-next bottom">{{ profile|days_left_by_year:1 }}</td>
            {% endwith %}
        </tr>
    </table>
</div>
<h2>New Holiday Request</h2>
<form method='POST'>
    {% if form_set %}
        {{ comment_form.as_p }}
        {{ form_set.management_form }}
        {% for form in form_set.forms %}
            {{ form.as_p }}
        {% endfor %}
        <p><input type="submit" value="Confirm"></p>
    {% else %}
        {{ hol_sel_form.as_p }}
        <p><input type="submit" value="Submit"></p>
    {% endif %}
</form>
{% endblock %}

holiday/templates/holiday/pending_requests.html
{% extends "holiday/base.html" %}
{% load holidaytags %}

{% block title %}Incuna Holiday Requests - Pending Requests{% endblock %}

{% block content %}
    <h2>Pending Holiday Requests</h2>
    {% for p in holidayrequest_list.all|dictsortreversed:"date_made" %}
        {% if forloop.first %}
        <table id="pending-requests" class="standardtable">
            <thead>
            <tr>
                <th>Holiday Begins</th>
                <th>Managed By</th>
                <th>Requested By</th>
                <th>Days Requested<br />(This / Next Year)</th>
                <th>Days Left Before<br />(This / Next Year)</th>
                <th>Days Left After<br />(This / Next Year)</th>
                <th class="noborder"></th>
            </tr>
            </thead>
        {% endif %}
        {% with p|days_requested_by_year as days_req_0 %}
        {% with p|days_requested_by_year:1 as days_req_1 %}
        {% with p.employee|days_left_by_year as days_left_0 %}
        {% with p.employee|days_left_by_year:1 as days_left_1 %}
            <tr>
                {% with p.holiday_set.all|first as first_hol %}
                    <td>{{ first_hol.date|date }}</td>
                {% endwith %}
                <td>{{ p.employee.manager.get_full_name }}</td>
                <td>{{ p.employee.get_full_name }}</td>
                <td>{{ days_req_0 }} / {{ days_req_1 }}</td>
                <td>{{ days_left_0 }} / {{ days_left_1 }}</td>
                <td>{{ days_left_0|subtract:days_req_0 }} / {{ days_left_1|subtract:days_req_1 }}</td>
                <td><a href="{% url holiday_request_details pk=p.pk %}">{% ifnotequal p.employee request.user %}Manage{% else %}Details{% endifnotequal %}</a></td>
            </tr>
        {% endwith %}{% endwith %}{% endwith %}{% endwith %}
        {% if forloop.last %}</table>{% endif %}
    {% empty %}
        <p>There are no pending requests</p>
    {% endfor %}
{% endblock %}

holiday/templates/holiday/request_details.html
{% extends "holiday/base.html" %}
{% load holidaytags %}

{% block title %}Incuna Holiday Requests - Request Details{% endblock %}

{% block content %}
    {% ifequal holiday_request.status 0 %}
        {% with holiday_request|days_requested_by_year as days_req_0 %}
        {% with holiday_request|days_requested_by_year:1 as days_req_1 %}
        {% with holiday_request.employee|days_left_by_year as days_left_0 %}
        {% with holiday_request.employee|days_left_by_year:1 as days_left_1 %}
        <div class="right clear-right">
            <table class="days-left-table">
                <thead>
                    <tr><th class="centre noborder" colspan="2">Before</th></tr>
                    <tr>
                        <th class="col-this">This Year:</th>
                        <th class="col-next">Next Year:</th>
                    </tr>
                </thead>
                <tr>
                    <td class="col-this bottom">{{ days_left_0 }}</td>
                    <td class="col-next bottom">{{ days_left_1 }}</td>
                </tr>
            </table>
        </div>
        <div class="right clear-right">
            <table class="days-left-table">
                <thead>
                    <tr><th class="centre noborder" colspan="2">After</th></tr>
                    <tr>
                        <th class="col-this">This Year:</th>
                        <th class="col-next">Next Year:</th>
                    </tr>
                </thead>
                <tr>
                    <td class="col-this bottom">{{ days_left_0|subtract:days_req_0 }}</td>
                    <td class="col-next bottom">{{ days_left_1|subtract:days_req_1 }}</td>
                </tr>
            </table>
        </div>
        {% endwith %}{% endwith %}{% endwith %}{% endwith %}
    {% endifequal %}
    <h2>Details for {{holiday_request}}</h2>
    <p><strong>Employee: </strong>{{holiday_request.employee.get_full_name}}</p>
    <p><strong>Time Requested: </strong>{{ holiday_request.date_made|date }} {{holiday_request.date_made|date:"H:i"}}</p>
    <p><strong>Status: </strong>{{ holiday_request.get_status_display }}{% if holiday_request.administrator %} by {{ holiday_request.administrator.get_full_name }} {% endif %}</p>
    {% if holiday_request.employee_comment %}
        <p><strong>{{holiday_request.employee.get_full_name}} commented:</strong></p>
        <div class="container">{{ holiday_request.employee_comment }}</div>
    {% endif %}
    {% if not hol_auth_form %}
        {% if holiday_request.manager_comment %}
            <p><strong>{{ holiday_request.administrator.get_full_name }} Commented:</strong></p>
            <div class="container">{{ holiday_request.manager_comment }}</div>
        {% endif %}
    {% endif %}
    <p><strong>Days Requested:</strong></p>
    <ul>
    {% for day in holidays.all %}
        <li>{{day}}</li>
    {% endfor %}
    </ul>
    {% if hol_auth_form %}
        <form method="POST">
            {{hol_auth_form.as_p}}
            <p class="clear"><input type="submit" value="Send"></p>
        </form>
    {% endif %}
{% endblock %}

holiday/templates/holiday/view_status.html
{% extends "holiday/base.html" %}
{% load holidaytags %}

{% block title %}Incuna Holiday Requests - {{employee.get_full_name}}{% endblock %}

{% block content %}
    <div class="right">
        <table class="days-left-table">
            <thead>
                <tr><th class="centre noborder" colspan="2">Days Remaining</th></tr>
                <tr>
                    <th class="col-this">This Year:</th>
                    <th class="col-next">Next Year:</th>
                </tr>
            </thead>
            <tr>
                <td class="col-this bottom">{{ employee|days_left_by_year }}</td>
                <td class="col-next bottom">{{ employee|days_left_by_year:1 }}</td>
            </tr>
        </table>
    </div>
    <h2>{{employee.get_full_name}}</h2>
    <p>Allowance days: {{ employee|days_left_by_year }}</p>
    <p><strong>Manager: </strong>{{employee.manager.get_full_name}}</p>
    {% with holidayrequest_list.all as hol_reqs %}
    {% if hol_reqs %}
        <h3>Submitted Requests</h3>
        <table class="standardtable" id="request-status">
            {% for hol_req in hol_reqs %}
            {% if forloop.first %}
            <thead>
            <tr>
                <th class="col-time">Holiday Begins</th>
                <th class="col-days">Days Requested</th>
                <th class="col-comment1">Employee Comment</th>
                <th class="col-comment2">Manager Comment</th>
                <th class="col-status">Status</th>
                <th class="col-link noborder"></th>
            </tr>
            </thead>
            {% endif %}
            <tr class="status{{ hol_req.status }}">
                {% with hol_req.holiday_set.all|first as first_hol %}
                <td class="col-time">{{ first_hol.date|date }}</td>
                {% endwith %}
                <td class="col-days">{{ hol_req.days_requested_total }}</td>
                <td class="col-comment1">{% if hol_req.employee_comment %}{{ hol_req.employee_comment|truncchar:30 }}{% else %}---{% endif %}</td>
                <td class="col-comment2">{% if hol_req.manager_comment %}{{ hol_req.manager_comment|truncchar:30 }}{% else %}---{% endif %}</td>
                <td class="col-status">{{ hol_req.get_status_display }}{% if hol_req.administrator %} by {{ hol_req.administrator.get_full_name }}{% endif %}</td>
                <td class="col-link"><a href="{% url holiday_request_details pk=hol_req.pk %}">Details</a></td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>No Requests Submitted</h3>
    {% endif %}
    {% endwith %}
{% endblock %}